import { Inspection, School, TimelineEvent, Document, Evidence, ChecklistSection, FinalReport } from '@/types';

const schools: School[] = [
  {
    id: 'school-001',
    name: 'Delhi Public School, RK Puram',
    address: 'Sector XII, RK Puram',
    city: 'New Delhi',
    state: 'Delhi',
    zipCode: '110022',
    phone: '+91 11 2617 1217',
    email: 'principal@dpsrkp.net',
    principalName: 'Dr. Anil Kumar Sharma',
    schoolType: 'public',
    totalStudents: 4500,
    establishedYear: 1972,
    coordinates: { latitude: 28.5562, longitude: 77.1734 },
  },
  {
    id: 'school-002',
    name: 'Modern School, Barakhamba Road',
    address: 'Barakhamba Road',
    city: 'New Delhi',
    state: 'Delhi',
    zipCode: '110001',
    phone: '+91 11 2331 6380',
    email: 'info@modernschool.net',
    principalName: 'Mrs. Priya Gupta',
    schoolType: 'public',
    totalStudents: 3200,
    establishedYear: 1920,
    coordinates: { latitude: 28.6289, longitude: 77.2266 },
  },
  {
    id: 'school-003',
    name: 'St. Xavier\'s School, Raj Niwas Marg',
    address: 'Raj Niwas Marg',
    city: 'Delhi',
    state: 'Delhi',
    zipCode: '110054',
    phone: '+91 11 2396 2103',
    email: 'stxaviersdelhi@gmail.com',
    principalName: 'Fr. Joseph Fernandes',
    schoolType: 'private',
    totalStudents: 2800,
    establishedYear: 1960,
    coordinates: { latitude: 28.6562, longitude: 77.2380 },
  },
  {
    id: 'school-004',
    name: 'Don Bosco School, Alaknanda',
    address: 'Alaknanda Road',
    city: 'New Delhi',
    state: 'Delhi',
    zipCode: '110019',
    phone: '+91 11 2602 8373',
    email: 'dbsalaknanda@gmail.com',
    principalName: 'Bro. Joseph Thomas',
    schoolType: 'private',
    totalStudents: 2100,
    establishedYear: 1980,
    coordinates: { latitude: 28.5289, longitude: 77.2501 },
  },
  {
    id: 'school-005',
    name: 'Sardar Patel Vidyalaya',
    address: 'Lodi Estate',
    city: 'New Delhi',
    state: 'Delhi',
    zipCode: '110003',
    phone: '+91 11 2464 2047',
    email: 'spv@spvdelhi.org',
    principalName: 'Dr. Meera Reddy',
    schoolType: 'public',
    totalStudents: 1800,
    establishedYear: 1958,
    coordinates: { latitude: 28.5916, longitude: 77.2193 },
  },
  {
    id: 'school-006',
    name: 'Springdales School, Pusa Road',
    address: 'Pusa Road',
    city: 'New Delhi',
    state: 'Delhi',
    zipCode: '110005',
    phone: '+91 11 2573 1554',
    email: 'springdales@vsnl.com',
    principalName: 'Mrs. Ameeta Mulla Wattal',
    schoolType: 'public',
    totalStudents: 2500,
    establishedYear: 1955,
    coordinates: { latitude: 28.6425, longitude: 77.1789 },
  },
];

const generateTimeline = (inspectionId: string, status: string): TimelineEvent[] => {
  const baseTimeline: TimelineEvent[] = [
    {
      id: `timeline-${inspectionId}-1`,
      inspectionId,
      type: 'application_submitted',
      title: 'Application Submitted',
      description: 'School submitted inspection application with all required documents.',
      timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      performedBy: 'School Admin',
      status: 'completed',
      icon: 'file-document',
      color: '#10B981',
    },
    {
      id: `timeline-${inspectionId}-2`,
      inspectionId,
      type: 'admin_approved',
      title: 'Admin Approved',
      description: 'Application reviewed and approved by department admin.',
      timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
      performedBy: 'Department Admin',
      status: 'completed',
      icon: 'check-circle',
      color: '#10B981',
    },
    {
      id: `timeline-${inspectionId}-3`,
      inspectionId,
      type: 'assigned_to_officer',
      title: 'Assigned to Officer',
      description: 'Inspection assigned to Inspector Rajesh Kumar.',
      timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
      performedBy: 'Supervisor',
      status: 'completed',
      icon: 'account-check',
      color: '#0B3D91',
    },
  ];

  if (status === 'pending' || status === 'assigned') {
    return baseTimeline;
  }

  baseTimeline.push({
    id: `timeline-${inspectionId}-4`,
    inspectionId,
    type: 'document_verification',
    title: 'Document Verification',
    description: 'Officer verified all submitted documents.',
    timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    performedBy: 'Inspector Rajesh Kumar',
    status: 'completed',
    icon: 'file-check',
    color: '#0F766E',
  });

  if (status === 'document_verification') {
    return baseTimeline;
  }

  baseTimeline.push({
    id: `timeline-${inspectionId}-5`,
    inspectionId,
    type: 'visit_scheduled',
    title: 'Visit Scheduled',
    description: 'Physical inspection scheduled.',
    timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    performedBy: 'Inspector Rajesh Kumar',
    status: 'completed',
    icon: 'calendar-check',
    color: '#C6A700',
  });

  if (status === 'scheduled') {
    return baseTimeline;
  }

  baseTimeline.push({
    id: `timeline-${inspectionId}-6`,
    inspectionId,
    type: 'inspection_started',
    title: 'Inspection Started',
    description: 'Physical inspection commenced at school premises.',
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    performedBy: 'Inspector Rajesh Kumar',
    status: 'completed',
    icon: 'play-circle',
    color: '#0B3D91',
  });

  if (status === 'in_progress') {
    return baseTimeline;
  }

  baseTimeline.push(
    {
      id: `timeline-${inspectionId}-7`,
      inspectionId,
      type: 'inspection_completed',
      title: 'Inspection Completed',
      description: 'Physical inspection completed successfully.',
      timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      performedBy: 'Inspector Rajesh Kumar',
      status: 'completed',
      icon: 'check-all',
      color: '#10B981',
    },
    {
      id: `timeline-${inspectionId}-8`,
      inspectionId,
      type: 'report_submitted',
      title: 'Report Submitted',
      description: 'Final inspection report submitted for review.',
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      performedBy: 'Inspector Rajesh Kumar',
      status: 'completed',
      icon: 'file-send',
      color: '#0F766E',
    }
  );

  if (status === 'completed') {
    return baseTimeline;
  }

  if (status === 'approved') {
    baseTimeline.push({
      id: `timeline-${inspectionId}-9`,
      inspectionId,
      type: 'final_approval',
      title: 'Final Approval',
      description: 'Inspection approved by department.',
      timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      performedBy: 'Department Head',
      status: 'completed',
      icon: 'certificate',
      color: '#10B981',
    });
  }

  if (status === 'rejected') {
    baseTimeline.push({
      id: `timeline-${inspectionId}-9`,
      inspectionId,
      type: 'rejection',
      title: 'Application Rejected',
      description: 'Inspection failed. Re-inspection required.',
      timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      performedBy: 'Department Head',
      status: 'completed',
      icon: 'close-circle',
      color: '#EF4444',
    });
  }

  return baseTimeline;
};

const generateDocuments = (inspectionId: string): Document[] => [
  {
    id: `doc-${inspectionId}-1`,
    inspectionId,
    type: 'registration',
    name: 'School Registration Certificate',
    fileUrl: 'https://example.com/docs/registration.pdf',
    fileType: 'pdf',
    status: 'verified',
    uploadedBy: 'School Admin',
    uploadedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    verifiedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    size: 2048000,
  },
  {
    id: `doc-${inspectionId}-2`,
    inspectionId,
    type: 'license',
    name: 'Operating License',
    fileUrl: 'https://example.com/docs/license.pdf',
    fileType: 'pdf',
    status: 'verified',
    uploadedBy: 'School Admin',
    uploadedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    verifiedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    size: 1536000,
  },
  {
    id: `doc-${inspectionId}-3`,
    inspectionId,
    type: 'insurance',
    name: 'Insurance Policy Document',
    fileUrl: 'https://example.com/docs/insurance.pdf',
    fileType: 'pdf',
    status: 'verified',
    uploadedBy: 'School Admin',
    uploadedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    verifiedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    size: 3072000,
  },
  {
    id: `doc-${inspectionId}-4`,
    inspectionId,
    type: 'safety_certificate',
    name: 'Fire Safety Certificate',
    fileUrl: 'https://example.com/docs/safety.pdf',
    fileType: 'pdf',
    status: Math.random() > 0.5 ? 'verified' : 'pending',
    uploadedBy: 'School Admin',
    uploadedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    verifiedAt: Math.random() > 0.5 ? new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString() : undefined,
    size: 1024000,
  },
  {
    id: `doc-${inspectionId}-5`,
    inspectionId,
    type: 'staff_qualification',
    name: 'Staff Qualification Records',
    fileUrl: 'https://example.com/docs/staff.pdf',
    fileType: 'pdf',
    status: 'pending',
    uploadedBy: 'School Admin',
    uploadedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    size: 4096000,
  },
];

const generateChecklist = (inspectionId: string): ChecklistSection[] => [
  {
    id: `check-${inspectionId}-infra`,
    inspectionId,
    title: 'Infrastructure',
    description: 'School building and facility assessment',
    order: 1,
    isExpanded: true,
    items: [
      { id: `item-${inspectionId}-1`, sectionId: `check-${inspectionId}-infra`, title: 'Building structure is sound and well-maintained', status: 'pass', isRequired: true, weight: 10, evidenceIds: [] },
      { id: `item-${inspectionId}-2`, sectionId: `check-${inspectionId}-infra`, title: 'Classrooms are adequately sized and ventilated', status: 'pass', isRequired: true, weight: 10, evidenceIds: [] },
      { id: `item-${inspectionId}-3`, sectionId: `check-${inspectionId}-infra`, title: 'Proper lighting and electrical fittings', status: 'pass', isRequired: true, weight: 8, evidenceIds: [] },
      { id: `item-${inspectionId}-4`, sectionId: `check-${inspectionId}-infra`, title: 'Clean drinking water facilities', status: 'pass', isRequired: true, weight: 10, evidenceIds: [] },
    ],
  },
  {
    id: `check-${inspectionId}-safety`,
    inspectionId,
    title: 'Safety',
    description: 'Safety and security measures',
    order: 2,
    isExpanded: false,
    items: [
      { id: `item-${inspectionId}-5`, sectionId: `check-${inspectionId}-safety`, title: 'Fire safety equipment installed and functional', status: 'pass', isRequired: true, weight: 10, evidenceIds: [] },
      { id: `item-${inspectionId}-6`, sectionId: `check-${inspectionId}-safety`, title: 'Emergency exits clearly marked and accessible', status: 'pass', isRequired: true, weight: 10, evidenceIds: [] },
      { id: `item-${inspectionId}-7`, sectionId: `check-${inspectionId}-safety`, title: 'First aid kit available and stocked', status: 'needs_improvement', comment: 'Needs more supplies', isRequired: true, weight: 8, evidenceIds: [] },
      { id: `item-${inspectionId}-8`, sectionId: `check-${inspectionId}-safety`, title: 'CCTV cameras installed at key locations', status: 'pass', isRequired: false, weight: 5, evidenceIds: [] },
    ],
  },
  {
    id: `check-${inspectionId}-staff`,
    inspectionId,
    title: 'Staff Verification',
    description: 'Teaching and non-teaching staff credentials',
    order: 3,
    isExpanded: false,
    items: [
      { id: `item-${inspectionId}-9`, sectionId: `check-${inspectionId}-staff`, title: 'All teachers have required qualifications', status: 'pass', isRequired: true, weight: 10, evidenceIds: [] },
      { id: `item-${inspectionId}-10`, sectionId: `check-${inspectionId}-staff`, title: 'Background verification completed for all staff', status: 'pass', isRequired: true, weight: 10, evidenceIds: [] },
      { id: `item-${inspectionId}-11`, sectionId: `check-${inspectionId}-staff`, title: 'Adequate student-teacher ratio maintained', status: 'pass', isRequired: true, weight: 8, evidenceIds: [] },
    ],
  },
  {
    id: `check-${inspectionId}-lab`,
    inspectionId,
    title: 'Lab Equipment',
    description: 'Science and computer laboratory facilities',
    order: 4,
    isExpanded: false,
    items: [
      { id: `item-${inspectionId}-12`, sectionId: `check-${inspectionId}-lab`, title: 'Science lab equipped with necessary apparatus', status: 'pass', isRequired: true, weight: 8, evidenceIds: [] },
      { id: `item-${inspectionId}-13`, sectionId: `check-${inspectionId}-lab`, title: 'Computer lab with adequate systems', status: 'pass', isRequired: true, weight: 8, evidenceIds: [] },
      { id: `item-${inspectionId}-14`, sectionId: `check-${inspectionId}-lab`, title: 'Internet connectivity available', status: 'pass', isRequired: false, weight: 5, evidenceIds: [] },
      { id: `item-${inspectionId}-15`, sectionId: `check-${inspectionId}-lab`, title: 'Lab safety protocols followed', status: 'pass', isRequired: true, weight: 8, evidenceIds: [] },
    ],
  },
  {
    id: `check-${inspectionId}-sanitation`,
    inspectionId,
    title: 'Sanitation',
    description: 'Cleanliness and hygiene facilities',
    order: 5,
    isExpanded: false,
    items: [
      { id: `item-${inspectionId}-16`, sectionId: `check-${inspectionId}-sanitation`, title: 'Clean and functional toilets', status: 'pass', isRequired: true, weight: 10, evidenceIds: [] },
      { id: `item-${inspectionId}-17`, sectionId: `check-${inspectionId}-sanitation`, title: 'Separate toilets for boys and girls', status: 'pass', isRequired: true, weight: 10, evidenceIds: [] },
      { id: `item-${inspectionId}-18`, sectionId: `check-${inspectionId}-sanitation`, title: 'Hand washing facilities with soap', status: 'pass', isRequired: true, weight: 8, evidenceIds: [] },
      { id: `item-${inspectionId}-19`, sectionId: `check-${inspectionId}-sanitation`, title: 'Waste disposal system in place', status: 'needs_improvement', comment: 'Improve segregation', isRequired: true, weight: 8, evidenceIds: [] },
    ],
  },
];

const generateEvidence = (inspectionId: string): Evidence[] => [
  {
    id: `evidence-${inspectionId}-1`,
    inspectionId,
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400',
    tag: 'classroom',
    description: 'Main classroom view',
    capturedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    capturedBy: 'Inspector Rajesh Kumar',
    fileSize: 2048000,
    isUploaded: true,
  },
  {
    id: `evidence-${inspectionId}-2`,
    inspectionId,
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1562774053-701939374585?w=400',
    tag: 'lab',
    description: 'Science laboratory',
    capturedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    capturedBy: 'Inspector Rajesh Kumar',
    fileSize: 1843200,
    isUploaded: true,
  },
  {
    id: `evidence-${inspectionId}-3`,
    inspectionId,
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    tag: 'safety',
    description: 'Fire extinguisher installation',
    capturedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    capturedBy: 'Inspector Rajesh Kumar',
    fileSize: 1536000,
    isUploaded: true,
  },
];

export const dummyInspections: Inspection[] = [
  {
    id: 'insp-001',
    schoolId: 'school-001',
    school: schools[0],
    officerId: 'officer-001',
    status: 'document_verification',
    priority: 'high',
    assignedDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: false,
    documents: generateDocuments('insp-001'),
    timeline: generateTimeline('insp-001', 'document_verification'),
    evidence: generateEvidence('insp-001'),
    checklist: generateChecklist('insp-001'),
    notes: 'High priority inspection due to previous compliance issues.',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'insp-002',
    schoolId: 'school-002',
    school: schools[1],
    officerId: 'officer-001',
    status: 'scheduled',
    priority: 'medium',
    assignedDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    scheduledDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: false,
    documents: generateDocuments('insp-002'),
    timeline: generateTimeline('insp-002', 'scheduled'),
    evidence: [],
    checklist: generateChecklist('insp-002'),
    notes: 'Scheduled for tomorrow at 10:00 AM.',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'insp-003',
    schoolId: 'school-003',
    school: schools[2],
    officerId: 'officer-001',
    status: 'pending',
    priority: 'urgent',
    assignedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: false,
    documents: generateDocuments('insp-003'),
    timeline: generateTimeline('insp-003', 'pending'),
    evidence: [],
    checklist: generateChecklist('insp-003'),
    notes: 'Urgent inspection required.',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'insp-004',
    schoolId: 'school-004',
    school: schools[3],
    officerId: 'officer-001',
    status: 'in_progress',
    priority: 'medium',
    assignedDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    scheduledDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: false,
    documents: generateDocuments('insp-004'),
    timeline: generateTimeline('insp-004', 'in_progress'),
    evidence: generateEvidence('insp-004'),
    checklist: generateChecklist('insp-004'),
    notes: 'Inspection in progress. Evidence collection ongoing.',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'insp-005',
    schoolId: 'school-005',
    school: schools[4],
    officerId: 'officer-001',
    status: 'completed',
    priority: 'low',
    assignedDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    scheduledDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: false,
    documents: generateDocuments('insp-005'),
    timeline: generateTimeline('insp-005', 'completed'),
    evidence: generateEvidence('insp-005'),
    checklist: generateChecklist('insp-005'),
    finalReport: {
      id: 'report-005',
      inspectionId: 'insp-005',
      overallScore: 85,
      riskCategory: 'low',
      recommendation: 'approve',
      summary: 'School meets all required standards with minor improvements needed.',
      strengths: ['Excellent infrastructure', 'Well-qualified staff', 'Good safety measures'],
      weaknesses: ['Minor sanitation issues', 'Limited lab equipment'],
      actionItems: ['Upgrade waste disposal system', 'Add more science lab apparatus'],
      submittedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
      submittedBy: 'Inspector Rajesh Kumar',
    },
    notes: 'Inspection completed successfully. Report approved.',
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'insp-006',
    schoolId: 'school-006',
    school: schools[5],
    officerId: 'officer-001',
    status: 'assigned',
    priority: 'high',
    assignedDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: true,
    documents: generateDocuments('insp-006'),
    timeline: generateTimeline('insp-006', 'assigned'),
    evidence: [],
    checklist: generateChecklist('insp-006'),
    notes: 'Overdue inspection. Immediate action required.',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export { schools };
